### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by jcassee** [DannyBen/docker-redirector#1]
Could you add a license file? I would like to adapt this project for myself, but without a license you retain full copyright. (If that is your intention, an explicit license makes that clear.)

**Comment by DannyBen** [comment]
Oh sure. Consider it MIT, I will add.

**Comment by DannyBen** [comment]
Closed via 24b5a55a50e52358091f2d806e99b7baa371c455 - enjoy.

**Comment by jcassee** [comment]
That was quick! :smile: Thank you.
