### ISSUE TITLE
keep query_args

### ISSUE THREAD

**Issue by cfoellmann** [DannyBen/docker-redirector#2]
Is it possible to redirect like

`origin.com/folder?arg=value => target.com/folder?arg=value` ?

Maybe it is easy for you to implement?

**Comment by DannyBen** [comment]
Currently not possible, and I see the code is out of date.
Let me do some housekeeping first, and then I think I can implement it with ease.

**Comment by DannyBen** [comment]
I just realized why this code is outdated... I migrated it to a new, much more flexible Ruby gem and docker image.

See https://github.com/dannyben/redirectly

I am currently updating it, but it should do what you need.
I will probably archive this repository.

**Comment by cfoellmann** [comment]
Perfect ! Thanks
